[nitpick]
minimum_version = "0.10.0"

[nitpick.styles]
include = [
  "resources/any/editorconfig",
  "resources/any/prettier",
  "resources/any/hooks",
  "resources/shell/bashate",

  # TODO: "resources/any/markdownlint",
  # TODO: "resources/shell/shellcheck",
  # maybe? "resources/any/commitizen",
]

[[".gitignore".contains]]
line = ".cache/"
