[[".clang-format".contains]]
line = "ColumnLimit: 120"

[[".clang-format".contains]]
line = "AccessModifierOffset: -1"

[[".clang-format".contains]]
line = "AlignAfterOpenBracket: DontAlign"

[".editorconfig".Makefile]
indent_style = "tab"
