[nitpick]
minimum_version = "0.10.0"

[nitpick.styles]
include = [
  "github://MrP01/lint-me-now/resources/python/37",
  "github://MrP01/lint-me-now/resources/python/poetry",
  "github://MrP01/lint-me-now/resources/python/black",
  "github://MrP01/lint-me-now/resources/python/isort",
  "github://MrP01/lint-me-now/resources/python/pylint",
  "github://MrP01/lint-me-now/resources/python/absent",
  "github://MrP01/lint-me-now/resources/python/bandit",
  "github://MrP01/lint-me-now/resources/python/flake8",
  "github://MrP01/lint-me-now/resources/python/hooks",
  "github://MrP01/lint-me-now/resources/python/mypy",
  "github://MrP01/lint-me-now/resources/python/github-workflow",
  "github://MrP01/lint-me-now/resources/python/autoflake",

  # maybe? "./resources/python/tox",
  # perhaps? "./resources/python/radon",
  # perhaps? "./resources/python/sonar-python",
  # doesn't really fit: "./resources/python/readthedocs",
]
