[[".clang-format".contains]]
line = "ColumnLimit: 120"

[[".clang-format".contains]]
line = "AccessModifierOffset: -1"

[[".clang-format".contains]]
line = "AlignAfterOpenBracket: DontAlign"

[[".clang-format".contains]]
line = "IndentCaseLabels: true"

[".editorconfig".Makefile]
indent_style = "tab"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/pre-commit/mirrors-clang-format"

[[".pre-commit-config.yaml".repos.hooks]]
id = "clang-format"
