[nitpick.styles]
include = [
  "resources/any/editorconfig",
  "resources/any/prettier",
  "resources/any/hooks",

  # TODO: "resources/any/markdownlint",
  # maybe? "resources/any/commitizen",
]

[[".gitignore".contains]]
line = ".cache/"
