[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/PyCQA/bandit"

[[".pre-commit-config.yaml".repos.hooks]]
id = "bandit"
args = ["-c", "pyproject.toml"]
exclude = "tests/"

["pyproject.toml".tool.bandit]
skips = ["B101"]
