[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/Riverside-Healthcare/djLint"

[[".pre-commit-config.yaml".repos.hooks]]
id = "djlint-jinja"
files = "\\.jinja"
args = ["--reformat", "--lint"]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/thibaudcolas/curlylint"

[[".pre-commit-config.yaml".repos.hooks]]
id = "curlylint"

["pyproject.toml".tool.djlint]
ignore = "T003,H023,J004"
max_line_length = 120
