[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/pre-commit/pygrep-hooks"

[[".pre-commit-config.yaml".repos.hooks]]
id = "python-check-blanket-noqa"

[[".pre-commit-config.yaml".repos.hooks]]
id = "python-check-mock-methods"

[[".pre-commit-config.yaml".repos.hooks]]
id = "python-no-eval"

[[".pre-commit-config.yaml".repos.hooks]]
id = "python-no-log-warn"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/asottile/pyupgrade"

[[".pre-commit-config.yaml".repos.hooks]]
id = "pyupgrade"
args = ["--py37-plus"]
