[nitpick.files.present]
"pyproject.toml" = "Install poetry and run 'poetry init' to create it"

["pyproject.toml".build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
