[[".pre-commit-config.yaml".repos]]
repo = "local"

[[".pre-commit-config.yaml".repos.hooks]]
id = "pyright"
name = "pyright"
entry = "pyright"
language = "system"
types = ["python"]
pass_filenames = false
