["pyproject.toml".tool.ruff]
line-length = 120
select = ["I001"]
exclude = [".git", "**/__pycache__"]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/charliermarsh/ruff-pre-commit"

[[".pre-commit-config.yaml".repos.hooks]]
id = "ruff"
