[[".gitignore".contains]]
line = "*.aux"
line = "*.log"
line = "*.idx"
line = "*.out"
line = "*.toc"
line = "*.synctex.gz"
line = "*.synctex(busy)"
line = "*.fdb_latexmk"
line = "*.fls"
line = "*.ilg"
line = "*.ind"
line = "_minted-*"
line = "*.bbl"
line = "*.bcf"
line = "*.blg"
line = "*.lof"
line = "*.lot"
line = "*.nlo"
line = "*.nls"
line = "*.run.xml"
line = ".~lock*"
line = "*.cb"
line = "*.cb2"
