[[".pre-commit-config.yaml".repos]]
repo = "local"

[[".pre-commit-config.yaml".repos.hooks]]
id = "prettier"
name = "prettier"
entry = "prettier --write --ignore-unknown"
language = "system"
types = ["text"]
