# Configuration file for Mega-Linter
# See all available variables at https://nvuillam.github.io/mega-linter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
DEFAULT_BRANCH: master # Usually master or main
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Comment to disable checks of abusive copy-pastes
  - SPELL # Comment to disable checks of spelling mistakes # - SPELL # Uncomment to disable checks of spelling mistakes
DISABLE_LINTERS:
  - PYTHON_MYPY
SHOW_ELAPSED_TIME: true
FILTER_REGEX_EXCLUDE: (mysolmate.eet.energy/app/|sol_admin/dist/|secrets/)
IGNORE_GITIGNORED_FILES: true
JAVASCRIPT_DEFAULT_STYLE: prettier
BASH_SHFMT_ARGUMENTS: "-i 2" # indent: 2 spaces
DOCKERFILE_DOCKERFILELINT_FILE_NAMES_REGEX: [".*Dockerfile"]
DOCKERFILE_HADOLINT_FILE_NAMES_REGEX: [".*Dockerfile"]
